# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='image')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('postid', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('like_num', models.IntegerField(default=0)),
                ('request_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_password', models.CharField(max_length=32)),
                ('u_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_icon', models.ImageField(upload_to='icons')),
                ('isDelete', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=16, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='like_movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movies'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
